# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 93ab503cbcadc0398f6c39b0e7d0b8a4cb7bec3ebf9fb8e8a79e862b100f92a6b3921be169aa5bc79c317e19642124693fd4854bf07896aff811c242e1688c9e

test:
  secret_key_base: d52f591d39740f05a3f0429f72006abdd02f8dba4238da3ee85fa8d8488219fb87a5eb61c80c8a3bf02ee3eb6e5c6176f2890530943ddcf9dafe73a26c62cc21

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
